[build]
  publish = "_site"
  command = "yarn build"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Robots-Tag = "noindex" 

[[redirects]]
  from = "/"
  to = "/admin/"
  status = 301